### ISSUE TITLE
Uvádění názvu custom typů v configu

### ISSUE THREAD

**Issue by Lexinek** [portiny/doctrine#2]
Ahoj, pro mě je to divné, proč musím uvádět název custom typu v configu, když se musí uvádět i přímo v php.

`abstract class Doctrine\DBAL\Types\Type` má totiž metodu `abstract public function getName();`, takže se musí uvádět. Přijde mi to jako duplikace.

Přecházím z `kdyby/doctrine`, tam stačilo uvést pouze pole s názvy tříd, a o ostatní se už postarala extension.

**Comment by TomasPilar** [comment]
Ahoj,

chápu, že na první pohled se to může zdát jako dvojta práce, ale ta metoda `getName` není statická, takže bych muset vytvářet objekt přes nějakou magii již při konfiguraci ORM v DI kontaineru. Tady je vidět jak se to dělá v Kdyby (https://github.com/Kdyby/Doctrine/blob/master/src/Kdyby/Doctrine/DI/OrmExtension.php#L515-L517). Vytvoří se objekt pro získání názvu a pak se objekt zase zahodí. 

Metody v `Type` jako `addType` nebo `hasType` ten název potřebují viz. https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Types/Type.php#L203 a než vykonávat nějakou zbytečnou inicializaci objektů v každém requestu, kvůli získání názvu mi přijde jako rychlejší a méně náročné uvést název typu již v konfiguraci.

Je škoda, že si to Doctrine neimplementuje sama, že by si název získala sama přes tu metodu. třeba se toho dočkáme v Doctrine 3.  :) V samotné třídě to mají poznačené zda je to vůbec potřeba https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Types/Type.php#L167 :D

**Comment by Lexinek** [comment]
Ok, díky za vysvětlení, budu tedy s očekáváním sledovat co se děje v doctrine 3 😄

**Comment by TomasPilar** [comment]
Díky za nápad! :)
